FROM ubuntu:18.04

#RUN apt-get update && \
#  apt-get install -y --no-install-recommends \
#   clang-9 make zsh vim curl gcc clang-9 lldb llvm valgrind g++ as31 nasm \
#	ruby ruby-bundler ruby-dev build-essential libx11-dev x11proto-core-dev \
#	libxt-dev libxext-dev libbsd-dev nasm freeglut3 libncurses5-dev glmark2 \
#	cmake git

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    clang-9 make curl cmake git ruby ruby-bundler ruby-dev build-essential

RUN git clone https://github.com/hivehelsinki/norminette-client.git /.norminette && \
	cd /.norminette && bundle && chmod 755 norminette.rb && ln -s /.norminette/norminette.rb /usr/bin/norminette
